### PR TITLE
Refactored parameter fetching code.

### PR DESCRIPTION
**Pull request by manwar**
Hi @nigelhorne 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Review by nigelhorne — COMMENTED** [review]
I have for months been intending to rewrite the parameter fetching code algorithm that I use throughout my code, probably as a wrapper to one of the existing validation modules.  This isn't the place for it, however, that place is my snippets repository.   I'm also not sure of this solution, but I will certainly consider it, thank you for your submission.

**Comment by manwar** [comment]
Point well taken :-)

**Comment by nigelhorne** [comment]
sub_name can probably come from

my $sub_name = (caller(1))[3];  #not checked this, but it's something like this

**Comment by manwar** [comment]
I tried that but it would give more than just sub name i.e. fully qualified sub name with package, which in my opinion, was crossing my limits ;-)

**Review by nigelhorne — APPROVED** [review]

**Pull request merged**
